\c PATIENTSDW;


/*
I am not using create dates or modify date columns quite literally only because this is not active. Personally would
suggest some kind of create/change tracking mechanism in a live production DB 
*/


CREATE TABLE MASTER_STATE (
    StateID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "State" TEXT -- revisit length
    --, "Abbrev" TEXT 
);

CREATE TABLE MASTER_CITY (
    CityID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "City" TEXT -- revisit length
);

CREATE TABLE MASTER_COUNTY (
    CountyID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "County" TEXT -- revisit length
);

CREATE TABLE MASTER_ADDRESS (
    AddressID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Address" TEXT -- revisit length
    
);

CREATE TABLE MASTER_GEO (
    CSCID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AddressID INT REFERENCES MASTER_ADDRESS(AddressID)
    CityID INT REFERENCES MASTER_CITY(CityID),
    CountyID INT REFERENCES MASTER_COUNTY(CountyID),
    StateID INT REFERENCES MASTER_STATE(StateID),
    Zip INT,
    LAT FLOAT,
    LON FLOAT,
    UNIQUE(AddressID,CityID,CountyID,StateID)
);

CREATE TABLE MASTER_NAME (
    NameID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT,
    FLMNameFlag BOOLEAN -- True: First, False: Last, NULL: MaidenName
);



---------------------------------------------------------------------------------------------------------------------
/*###################################################################################################################

                                                MASTER TABLES ABOVE

###################################################################################################################*/
---------------------------------------------------------------------------------------------------------------------

CREATE TABLE PATIENTS (
    PatientID UUID PRIMARY KEY, --- so we can still track patient encounter / cost cpverage from payers
    Healthcare_Expense FLOAT,
    Healthcare_Coverage FLOAT
);

/*
---- Need to make a seperate, more restrictive DB for this type of data
CREATE TABLE PATIENTS_IDENTIFICATION (
    PatientID UUID NOT NULL PRIMARY KEY REFERENCES PATIENTS(PatientID)
    SSN UUID NOT NULL,
    Driver TEXT UUID,
    Passport TEXT UUID
)-- technically speaking, it would be useful to cybercriminals to see how one might go about 
--- setting this up so i will pretend that the non-inclusion part is completely safety driven
--- while still mentioning *yes* we should still store this data in any kind of patient
--- driven data application in healthcare/pharma (*big brain expansion*)
*/
CREATE TABLE PATIENTS_GEOGRAPHIC_DATA (
    PatientID UUID NOT NULL PRIMARY KEY REFERENCES PATIENTS(PatientID)
    CSCID INT NOT NULL REFERENCES MASTER_GEO(CSCID)
    BirthplaceID INT NOT NULL REFERENCES MASTER_Geo(CSCID) -- can be birthed one place, live another
);


CREATE TABLE PATIENTS_DEMOGRAPHIC_DATA (
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    SPGM_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstNameID INT NOT NULL REFERENCES MASTER_NAME(NameID),
    LastNameID INT NOT NULL REFERENCES MASTER_NAME(NameID),
    Suffix TEXT,
    Prefix TEXT,
    Gender BOOLEAN,
    Married CHAR(1) -- M: Married, S: Single, NULL: Anything else
);


CREATE TABLE ORGANIZATIONS (
    OrgID UUID NOT NULL PRIMARY KEY,
    CSCID INT REFERENCES MASTER_GEO(CSCID) ON DELETE RESTRICT,
    PhoneID INT, 
    -- No revenue (all 0s) is seen in EDA, we will not incorporate
    Utilization INT
);

CREATE TABLE PROVIDERS (
    ProviderID UUID NOT NULL PRIMARY KEY,
    OrgID UUID NOT NULL REFERENCES ORGANIZATIONS(OrgID) DELETE ON CASCADE, -- should be able to reuse from GenderID

    Utilization INT
);

CREATE TABLE PROVIDERS_DETAILS (
    ProvierID UUID NOT NULL PRIMARY KEY REFERENCES PROVIDERS(ProviderID),
    FirstNameID INT NOT NULL REFERENCES MASTER_NAME(NameID),
    LastNameID INT NOT NULL REFERENCES MASTER_NAME(NameID),
    Gender BOOLEAN, -- TRUE: Female, FALSE: Male, NULL: Non-binary
    SpecialityID INT, -- will need to map these IDs
    CSCID INT REFERENCES MASTER_GEO(CSCID) ON DELETE NULL
)


CREATE TABLE PAYERS (
    PayerID UUID NOT NULL PRIMARY KEY, -- might need to change this, it seems to be unique but if hash does not
                                       -- maintain difference across states, we might need to create a composite prim key
    PayerName Text
);

CREATE TABLE PAYERS_GEOCONTACT_DATA (
    PayerID UUID NOT NULL PRIMARY KEY REFERENCES PAYERS(PayerID)
    CSCID INT NOT NULL REFERENCES MASTER_GEO(CSCID),
    Phone TEXT
);

CREATE TABLE PAYERS_COVERAGE_DETAILS (
    PayerID UUID NOT NULL PRIMARY KEY REFERENCES PAYERS(PayerID)
    AmountCovered NUMERIC(12,2),
    AmountUncovered NUMERIC(12,2),
    Revenue NUMERIC(12,2),
    CoveredEncounters INT,
    UncoveredEncounters INT,
    CoveredMedications INT,
    UncoveredMedications INT,
    CoveredProcedures INT,
    UncoveredProcedures INT,
    CoveredImmunizations INT,
    UncoveredImmunizations INT,
    UniqueCustomers INT,
    QOLS_AVG FLOAT,
    MemberMonths INT
);


---------------- ENCOUNTERS 
CREATE TABLE ENCOUNTER_CLASSES (
    EncounterClassID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EncounterClass TEXT
);


CREATE TABLE ENCOUNTER_VISIT_CODES (
    VisitCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString TEXT,
    "Description" TEXT,
    DescriptionDetail TEXT 
);


CREATE TABLE ENCOUNTER_REASON_CODES (
    ReasonCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString TEXT,
    "Description" TEXT,
    DescriptionDetail TEXT
);

CREATE TABLE ENCOUNTER_DETAILS (
    EncDetailID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EncounterClassID INT NOT NULL REFERENCES ENCOUNTER_CLASSES(EncounterClassID),
    VisitCode INT NOT NULL REFERENCES ENCOUNTER_VISIT_CODES(VisitCode),
    ReasonCode INT NOT NULL REFERENCES ENCOUNTER_REASON_CODES(ReasonCode)
);

CREATE TABLE ENCOUNTERS (
    EncounterID UUID NOT NULL PRIMARY KEY,
    "Start" TIMESTAMPTZ,
    "Stop" TIMESTAMPTZ,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    OrgID UUID NOT NULL REFERENCES ORGANIZATIONS(OrgID),
    ProviderID UUID NOT NULL REFERENCES PROVIDERS(ProviderID),
    PayerID UUID NOT NULL REFERENCES PAYERS(PayerID),
    BaseEncounterCost NUMERIC(12,2),
    TotalClaimCost  NUMERIC(12,2),
    Payer_Coverage  NUMERIC(12,2),
    EncDetailID INT NOT NULL REFERENCES ENCOUNTER_DETAILS(Code), -- will work as mapping join
    -- ReasonDescriptionID INT -- this will be added to the non-paren extract list since reasoncode already does the join we need
);


------------------------- CLAIMS
CREATE TABLE CLAIM_DIAGNOSIS_CODES (
    DiagnosisCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DiagnosisCodeString TEXT
);

CREATE TABLE CLAIMS_DIAGNOSIS (
    DiagnosisID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DiagnosisCode1 INT NOT NULL REFERENCES CLAIM_DIAGNOSIS_CODES(DiagnosisCode),
    DiagnosisCode2 INT REFERENCES CLAIM_DIAGNOSIS_CODES(DiagnosisCode),
    DiagnosisCode3 INT REFERENCES CLAIM_DIAGNOSIS_CODES(DiagnosisCode),
    DiagnosisCode4 INT REFERENCES CLAIM_DIAGNOSIS_CODES(DiagnosisCode),
    DiagnosisCode5 INT REFERENCES CLAIM_DIAGNOSIS_CODES(DiagnosisCode),
    DiagnosisCode6 INT REFERENCES CLAIM_DIAGNOSIS_CODES(DiagnosisCode),
    DiagnosisCode7 INT REFERENCES CLAIM_DIAGNOSIS_CODES(DiagnosisCode),
    DiagnosisCode8 INT REFERENCES CLAIM_DIAGNOSIS_CODES(DiagnosisCode)
);


CREATE TABLE CLAIMS (
    ClaimID UUID NOT NULL PRIMARY KEY,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    ProviderID UUID NOT NULL REFERENCES PROVIDERS(ProviderID)
    PrimaryPatientInsuranceID UUID NOT NULL, -- this likely references payers
    SecPatientInsuranceID UUID,
    DeptID SMALLINT,
    PatientDeptID INT,
    DiagnosisID INT REFERENCES CLAIMS_DIAGNOSIS(DiagnosisID),
    AppointmentID UUID NOT NULL,
    CurrentIllnessDate TIMESTAMPTZ,
    ServiceDate TIMESTAMPTZ,
    SupervisingProviderID UUID,
    Status1ID BOOLEAN, -- NULL: nan, 0:BILLED, 1:CLOSED
    Status2ID BOOLEAN, -- NULL: nan, 0:BILLED, 1:CLOSED
    StatusPID BOOLEAN, -- NULL: nan, 0:BILLED, 1:CLOSED
    -- all of the outstanding columns were zero or nan, does not make sense to include for scope of project
    LastBillDate1 TIMESTAMPTZ,
    LastBillDate2 TIMESTAMPTZ,
    LastBillDateP TIMESTAMPTZ,
    HealthCareClaimTypeID1 SMALLINT,
    HealthCareClaimTypeID2 SMALLINT
);

--- Claims Transactions
CREATE TABLE CLAIMSTRANSACTIONS_TYPES (
    TransTypeID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransTypeString TEXT
);

CREATE TABLE CLAIMSTRANSACTIONS_PAYMENT_METHODS (
    PaymentMethodID SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PaymentMethod TEXT
);

CREATE TABLE CLAIMSTRANSACTIONS_PAYMENT_DETAILS (
    PaymentDetailID SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransTypeID SMALLINT REFERENCES CLAIMSTRANSACTIONS_TYPES(TransTypeID),
    PaymentMethodID SMALLINT REFERENCES CLAIMSTRANSACTIONS_TYPES(PaymentMethodID)
);

CREATE TABLE CLAIMSTRANSACTIONS_PROCEDURE_CODES (
    ProcCodeID SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProcCodeString TEXT
);

CREATE TABLE CLAIMSTRANSACTIONS_NOTES ( -- add notes as a place to NOT extract parentheses
    NoteID SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NoteString TEXT
);

CREATE TABLE CLAIMSTRANSACTIONS (
    TransactionID UUID NOT NULL PRIMARY KEY,
    ClaimID UUID NOT NULL REFERENCES CLAIMS(ClaimID)
    ChargeID FLOAT,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    PaymentDetailID SMALLINT NOT NULL REFERENCES CLAIMSTRANSACTIONS_PAYMENT_DETAILS(PaymentMethodID),
    Amount  NUMERIC(12,2),
    FromDate TIMESTAMPTZ,
    ToDate TIMESTAMPTZ,
    PlaceOfServiceID UUID NOT NULL /* this most likely references a location, we will need to find this:
                                     REFERENCES ORGANIZATIONS(OrgID) | REFERENCES PROVIDERS(ProviderID) */,
    ProcCodeID SMALLINT NOT NULL REFERENCES CLAIMSTRANSACTIONS_PROCEDURE_CODES(ProcCodeID),
    DiagnosisRef1 BOOLEAN, -- since all of these are either a numeric or null, these are really just flags vv*5
    DiagnosisRef2 BOOLEAN,
    DiagnosisRef3 BOOLEAN,
    DiagnosisRef4 BOOLEAN,
    Units BOOLEAN,
    DeptID SMALLINT,
    NoteID SMALLINT REFERENCES CLAIMSTRANSACTIONS_NOTES(NoteID), --- need to string to int
    UnitAmount NUMERIC(12,2),
    TransferOutID INT,
    TransferTypeID INT,
    Payments NUMERIC(12,2),
    -- Adjustments FLOAT,
    Transfers NUMERIC(12,2),
    Outstanding NUMERIC(12,2),
    AppointmentID UUID NOT NULL REFERENCES CLAIMS(AppointmentID)
    -- LineNoteID INT,
    PatientInsuranceID UUID /*REFERENCES PAYERS(PayerID)*/,
    FeeScheduleID BOOLEAN,
    ProviderID UUID NOT NULL REFERENCES PROVIDERS(ProviderID)
    SupervisingProviderID UUID NOT NULL REFERENCES PROVIDERS(ProviderID) ON DELETE CASCADE
    /*
    I went back and forth on these last two since it is less of an issue to keep HCP data. However,
    since the lens of this project is to look at claims joruney's across prov/orgs/locations, we will assume
    the hypothetical stakeholder only wants data relevant where we can see the full picture and
    will cascade on delete.
    */
);

CREATE TABLE PAYERTRANSITIONS (
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    MemberID UUID NOT NULL REFERENCES PAYERS(PatientID)
    StartYear TIMESTAMPTZ,
    EndYear TIMESTAMPTZ,
    PrimPayerID UUID NOT NULL REFERENCES PAYERS(PayerID),
    SecPayerID UUID NOT NULL REFERENCES PAYERS(PayerID),
    /*
    No cascade on delete! Payer info is important for us and seeing where it comes from is important...
    BUTTTT
    identifying willing-payer opportunities does not necessarily need the org. 
    We will handle this by creating an 'Unidentified Payer' bucket
    */
    OwnershipID INT,
    OwnerNameID INT
);

-------------- Careplans

CREATE TABLE CAREPLAN_REASONCODES (
    Code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString TEXT,
    "Description" TEXT,
    ParenthesesDetail TEXT
);

CREATE TABLE CAREPLANS (
    CareplanID UUID NOT NULL PRIMARY KEY,
    "Start" TIMESTAMPTZ,
    "End" TIMESTAMPTZ,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID) ON DELETE CASCADE
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID)
    CareplanCode BIGINT NOT NULL REFERENCES CAREPLAN_CODES(Code)
);

-------------- Procedures

CREATE TABLE PROCEDURES_REASONCODES (
    ReasonCode FLOAT ,
    ReasonDescription TEXT,
    ParenthesesDetailDetail TEXT
);

CREATE TABLE PROCEDURES (
    ProcedureEventID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Start" TIMESTAMPTZ,
    "End" TIMESTAMPTZ,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID)
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID),
    ProcCode FLOAT NOT NULL,
    "Description" TEXT,
    BaseCost NUMERIC(12,2),
    ReasonCode FLOAT NOT NULL
);


-------------- Observation

CREATE TABLE OBSERVATION_CATEGORIES (
    CategoryID SMALLINT NOT NULL PRIMARY KEY,
    Category TEXT
);

CREATE TABLE OBSERVATION_CODES (
    Code SMALLINT NOT NULL PRIMARY KEY,
    "Description" TEXT,
    DescriptionDetail TEXT
);


CREATE TABLE OBSERVATIONS (
    "Date" TIMESTAMPTZ,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID)
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID),
    CategoryID SMALLINT NOT NULL REFERENCES OBSERVATION_CATEGORIES(CategoryID),
    ObservationCode SMALLINT NOT NULL REFERENCES OBSERVATION_CODES(Code),
    NumericOrText BOOLEAN -- True: Num, False: text
);

-------------- Medications
CREATE TABLE MEDICATION_CODES (
    MedCode SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString TEXT,
    "Description" TEXT,
    ParenthesesDetail TEXT
);

CREATE TABLE MEDICATION_REASON_CODE (
    ReasCode SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString TEXT,
    "Description" TEXT,
    ParenthesesDetail TEXT
);

CREATE TABLE MEDICATIONS (
    MedicationEventID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Start" TIMESTAMPTZ,
    "Stop" TIMESTAMPTZ,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    PayerID UUID NOT NULL REFERENCES PAYERS(PayerID),
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID)
    MedicationCode SMALLINT NOT NULL REFERENCES MEDICATION_CODES(MedCode),
    BaseCost NUMERIC(12,2),
    PayerCoverage NUMERIC(12,2),
    Dispenses INT,
    TotalCost NUMERIC(12,2),
    ReasonCode SMALLINT NOT NULL REFERENCES MEDICATION_REASON_CODE(ReasCode)
);

-------------- Immunizations
CREATE TABLE IMMUNIZATION_CODES (
    Code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString TEXT,
    "Description" TEXT,
    ParenthesesDetail TEXT
);


CREATE TABLE IMMUNIZATIONS (
    ImmunizationEventID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Date" TIMESTAMPTZ,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID)
    ImmunizationCode INT NOT NULL REFERENCES IMMUNIZATION_CODES(Code),
    BaseCost FLOAT
);


--------------  CONDITIONS
CREATE TABLE CONDITION_CODES (
    Code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString TEXT,
    "Description" TEXT,
    ParenthesesDetail TEXT
);

CREATE TABLE CONDITIONS (
    ConditionEventID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    "Start" TIMESTAMPTZ,
    "Stop" TIMESTAMPTZ,
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID)
    ConditionCode INT NOT NULL REFERENCES CONDITION_CODES(Code)
);


--------------  Images
CREATE TABLE IMAGINGSTUDIES_SERIESUID (
    SeriesUID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SeriesUIDString TEXT
);

CREATE TABLE IMAGINGSTUDIES_BODYSITE_CODES (
    Code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString TEXT,
    Bodysite TEXT -- add this to no paren extract since these parentheses do not mean anything
);

CREATE TABLE IMAGINGSTUDIES_MODALITY(
    Code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodeString
    ModalityAbbrev CHAR(2),
    Modality TEXT
);

CREATE TABLE IMAGINGSTUDIES_INSTANCEUID (
    InstanceUID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    InstanceUIDString TEXT
);

CREATE TABLE IMAGINGSTUDIES_SOPs (
    SOPiD INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SOP_CODE TEXT,
    SOP_DESCRIPTION TEXT
);

CREATE TABLE IMAGINGSTUDIES_PROCCODES (
    ProcCodeID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProcCodeString TEXT
);


CREATE TABLE IMAGINGSTUDIES (
    ImgStudyID UUID PRIMARY KEY,
    "Date" TIMESTAMPTZ,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID)
    SeriesUIDIntID INT NOT NULL REFERENCES IMAGINGSTUDIES_SERIESUID(SeriesUIDIntID),
    BodysiteCode INT NOT NULL REFERENCES IMAGINGSTUDIES_BODYSITE_CODES(Code),
    ModalityCode INT NOT NULL REFERENCES IMAGINGSTUDIES_MODALITY(Code),
    InstanceUIDIntID INT NOT NULL REFERENCES IMAGINGSTUDIES_INSTANCEUID(InstanceUIDIntID),
    SOPiD INT NOT NULL REFERENCES IMAGINGSTUDIES_SOPs(SOPiD),
    ProcCodeID INT NOT NULL REFERENCES IMAGINGSTUDIES_PROCCODES(ProcCodeID)
);

-------------- Devices
CREATE TABLE DEVICE_CODES (
    Code INT NOT NULL
    "Description" TEXT,
    DescriptionDetail TEXT
);

CREATE TABLE DEVICE_UDI (
    UDIID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UDIString TEXT,
    gtin BIGINT,
    ProdDate INT,
    ExpDate INT,
    LOT INT,
    SerialID INT
);

CREATE TABLE DEVICES (
    DeviceID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Start" TIMESTAMPTZ NULL,
    "Stop" TIMESTAMPTZ NULL,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID), 
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID)
    Code INT,
    UDIID INT
);

-------------- Allergies
CREATE TABLE ALLERGY_CODES (
    AllergyCode INT NOT NULL PRIMARY KEY,
    "Description" Text,
    DescriptionDetail TEXT
);

CREATE TABLE ALLERGY_SEVERITY (
    SeverityID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Severity TEXT -- map nulls to 'NONE' or 'NEGLIGIBLE' or 'UNNOTED' so no issues occur later (this can be modified later)
);

CREATE TABLE ALLERGY_REACTIONS (
    ReactionCode INT NOT NULL PRIMARY KEY,
    Reaction1Code TEXT,
    Reaction1Desc TEXT,
    Severity1 INT REFERENCES ALLERGY_SEVERITY(SeverityID),
    Reaction2Code TEXT,
    Reaction2Desc TEXT,
    Severity2 INT REFERENCES ALLERGY_SEVERITY(SeverityID)
);

CREATE TABLE ALLERGY_CATEGORIES (
    AllergyCategoryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    AllergyType CHAR(2), -- Al: Allergy, It: Intolerance
    AllergyCategory TEXT,
    ReactionCode INT NOT NULL REFERENCES ALLERGY_REACTIONS(Code)
);

CREATE TABLE ALLERGIES (
    AllergyEventID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Start" TIMESTAMPTZ NULL,
    "Stop" TIMESTAMPTZ NULL,
    PatientID UUID NOT NULL REFERENCES PATIENTS(PatientID),
    EncounterID UUID NOT NULL REFERENCES ENCOUNTERS(EncounterID)
    AllergyCode INT NOT NULL REFERENCES ALLERGY_CODES(AllergyCode),
    ReactionCode INT NOT NULL REFERENCES ALLERGY_REACTIONS(ReactionCode),
    AllergyCategoryID INT NULL REFERENCES ALLERGY_CATEGORIES(AllergyCode)
);




